"""
CompileViz Code Generator
Generates Three-Address Code (TAC) and executable Python output.
"""

from .parser import ASTNode
from typing import List


class CodeGenerator:
    def __init__(self):
        self.tac = []          # Three-address code instructions
        self.python_code = []  # Equivalent Python code
        self.temp_count = 0
        self.label_count = 0
        self.indent = 0

    def new_temp(self) -> str:
        self.temp_count += 1
        return f"t{self.temp_count}"

    def new_label(self) -> str:
        self.label_count += 1
        return f"L{self.label_count}"

    def emit_tac(self, instr: str):
        self.tac.append(instr)

    def emit_py(self, line: str):
        self.python_code.append("    " * self.indent + line)

    def generate(self, ast: ASTNode):
        self.emit_py("# Generated by CompileViz")
        self.emit_py("# MiniLang → Python Compiler Output")
        self.emit_py("")
        self.emit_tac("# === Three-Address Code ===")
        self.visit(ast)
        return self.tac, self.python_code

    def visit(self, node: ASTNode) -> str:
        method = f'gen_{node.node_type}'
        generator = getattr(self, method, self.generic_gen)
        return generator(node)

    def generic_gen(self, node: ASTNode):
        for child in node.children:
            if isinstance(child, ASTNode):
                self.visit(child)
        return ""

    def gen_Program(self, node: ASTNode):
        for child in node.children:
            if isinstance(child, ASTNode):
                self.visit(child)

    def gen_Declaration(self, node: ASTNode):
        name_node = node.children[1] if len(node.children) > 1 else None
        expr_node = node.children[2] if len(node.children) > 2 else None
        name = name_node.value if name_node else "?"

        if expr_node:
            result = self.visit(expr_node)
            self.emit_tac(f"{name} = {result}")
            self.emit_py(f"{name} = {result}")
        else:
            self.emit_tac(f"{name} = None")
            self.emit_py(f"{name} = None")
        return name

    def gen_Assignment(self, node: ASTNode):
        name = node.value
        expr = self.visit(node.children[1]) if len(node.children) > 1 else "None"
        self.emit_tac(f"{name} = {expr}")
        self.emit_py(f"{name} = {expr}")
        return name

    def gen_BinaryOp(self, node: ASTNode) -> str:
        left = self.visit(node.children[0]) if node.children else "?"
        right = self.visit(node.children[1]) if len(node.children) > 1 else "?"
        op = node.value
        # Map operators
        op_map = {'&&': 'and', '||': 'or', '==': '==', '!=': '!='}
        py_op = op_map.get(op, op)
        t = self.new_temp()
        self.emit_tac(f"{t} = {left} {op} {right}")
        return f"({left} {py_op} {right})"

    def gen_UnaryOp(self, node: ASTNode) -> str:
        operand = self.visit(node.children[0]) if node.children else "?"
        t = self.new_temp()
        self.emit_tac(f"{t} = -{operand}")
        return f"-{operand}"

    def gen_Integer(self, node: ASTNode) -> str:
        return node.value

    def gen_Float(self, node: ASTNode) -> str:
        return node.value

    def gen_String(self, node: ASTNode) -> str:
        return node.value

    def gen_Boolean(self, node: ASTNode) -> str:
        return 'True' if node.value == 'true' else 'False'

    def gen_Identifier(self, node: ASTNode) -> str:
        return node.value

    def gen_IfStatement(self, node: ASTNode):
        cond_node = node.children[0] if node.children else None
        then_node = node.children[1] if len(node.children) > 1 else None
        else_node = node.children[2] if len(node.children) > 2 else None

        L_true = self.new_label()
        L_false = self.new_label()
        L_end = self.new_label()

        cond = ""
        if cond_node and cond_node.children:
            cond = self.visit(cond_node.children[0])

        self.emit_tac(f"if {cond} goto {L_true}")
        self.emit_tac(f"goto {L_false}")
        self.emit_tac(f"{L_true}:")

        self.emit_py(f"if {cond}:")
        self.indent += 1
        if then_node:
            for child in then_node.children:
                if isinstance(child, ASTNode):
                    self.visit(child)
        if not (then_node and then_node.children):
            self.emit_py("pass")
        self.indent -= 1

        if else_node:
            self.emit_tac(f"goto {L_end}")
            self.emit_tac(f"{L_false}:")
            self.emit_py("else:")
            self.indent += 1
            for child in else_node.children:
                if isinstance(child, ASTNode):
                    self.visit(child)
            self.indent -= 1
            self.emit_tac(f"{L_end}:")
        else:
            self.emit_tac(f"{L_false}:")

    def gen_WhileLoop(self, node: ASTNode):
        cond_node = node.children[0] if node.children else None
        body_node = node.children[1] if len(node.children) > 1 else None

        L_start = self.new_label()
        L_end = self.new_label()

        cond = ""
        if cond_node and cond_node.children:
            cond = self.visit(cond_node.children[0])

        self.emit_tac(f"{L_start}:")
        self.emit_tac(f"if not ({cond}) goto {L_end}")

        self.emit_py(f"while {cond}:")
        self.indent += 1
        if body_node:
            for child in body_node.children:
                if isinstance(child, ASTNode):
                    self.visit(child)
        if not (body_node and body_node.children):
            self.emit_py("pass")
        self.indent -= 1

        self.emit_tac(f"goto {L_start}")
        self.emit_tac(f"{L_end}:")

    def gen_ForLoop(self, node: ASTNode):
        init_node = node.children[0] if node.children else None
        cond_node = node.children[1] if len(node.children) > 1 else None
        update_node = node.children[2] if len(node.children) > 2 else None
        body_node = node.children[3] if len(node.children) > 3 else None

        if init_node and init_node.children:
            self.visit(init_node.children[0])

        L_start = self.new_label()
        L_end = self.new_label()
        cond = ""
        if cond_node and cond_node.children:
            cond = self.visit(cond_node.children[0])

        self.emit_tac(f"{L_start}:")
        self.emit_tac(f"if not ({cond}) goto {L_end}")

        self.emit_py(f"# for loop (converted to while)")
        self.emit_py(f"while {cond}:")
        self.indent += 1
        if body_node:
            for child in body_node.children:
                if isinstance(child, ASTNode):
                    self.visit(child)
        if update_node and update_node.children:
            self.visit(update_node.children[0])
        if not (body_node and body_node.children):
            self.emit_py("pass")
        self.indent -= 1
        self.emit_tac(f"goto {L_start}")
        self.emit_tac(f"{L_end}:")

    def gen_FunctionDef(self, node: ASTNode):
        name = node.value
        params_node = node.children[0] if node.children else None
        body_node = node.children[1] if len(node.children) > 1 else None

        params = []
        if params_node:
            for p in params_node.children:
                parts = p.value.split()
                if len(parts) == 2:
                    params.append(parts[1])

        self.emit_tac(f"func {name}({', '.join(params)}):")
        self.emit_py(f"def {name}({', '.join(params)}):")
        self.indent += 1
        if body_node:
            for child in body_node.children:
                if isinstance(child, ASTNode):
                    self.visit(child)
        if not (body_node and body_node.children):
            self.emit_py("pass")
        self.indent -= 1
        self.emit_tac(f"end func {name}")
        self.emit_py("")

    def gen_FunctionCall(self, node: ASTNode) -> str:
        name = node.value
        args = [self.visit(c) for c in node.children if isinstance(c, ASTNode)]
        call_str = f"{name}({', '.join(args)})"
        t = self.new_temp()
        self.emit_tac(f"{t} = call {call_str}")
        self.emit_py(call_str)
        return call_str

    def gen_Print(self, node: ASTNode):
        args = [self.visit(c) for c in node.children if isinstance(c, ASTNode)]
        self.emit_tac(f"print {', '.join(args)}")
        self.emit_py(f"print({', '.join(args)})")

    def gen_Return(self, node: ASTNode):
        val = self.visit(node.children[0]) if node.children else ""
        self.emit_tac(f"return {val}")
        self.emit_py(f"return {val}")

    def gen_Condition(self, node: ASTNode) -> str:
        if node.children:
            return self.visit(node.children[0])
        return ""

    def gen_Name(self, node: ASTNode) -> str:
        return node.value


def generate(ast: ASTNode):
    gen = CodeGenerator()
    tac, python_code = gen.generate(ast)
    return tac, python_code
